name: phpunit
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          php_version: 8
          args: tests
